apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: test1
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.nvidia.com/gpu: 4
